<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="memory"
    nsURI="http://gb.hu/embedded/memory" nsPrefix="mem">
  <eClassifiers xsi:type="ecore:EClass" name="RAMModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//MemSegment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ram" eType="#//RAMModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prog" eType="#//ProgModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemSegment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAddr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgModel" eSuperTypes="#//MemSegment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resetVector" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
</ecore:EPackage>
