
/*
 * generated by Xtext
 */
 
package hu.cubussapiens.modembed.modularasm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class ModularASMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return hu.cubussapiens.modembed.modularasm.ui.internal.ModularASMActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return hu.cubussapiens.modembed.modularasm.ui.internal.ModularASMActivator.getInstance().getInjector("hu.cubussapiens.modembed.modularasm.ModularASM");
	}
	
}
