/*
* generated by Xtext
*/
package hu.cubussapiens.modembed.modularasm.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ModularASMTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
