<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modularASM"
    nsURI="http://www.cubussapiens.hu/modembed/modularasm/ModularASM" nsPrefix="modularASM">
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//QualifiedID"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ModuleItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//ModuleParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//QualifiedID"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedID">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="segments" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationWord" eSuperTypes="#//ModuleItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//LiteralParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//ConfigurationFieldPlace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationFieldPlace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bitNum" eType="#//LiteralParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startBit" eType="#//LiteralParam"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//ConfigurationField"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationField"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumConfigurationField" eSuperTypes="#//ConfigurationField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumConfigurationFieldLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumConfigurationFieldLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//LiteralParam"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="#//ModuleItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//ModuleItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//ModuleItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//QualifiedID"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//ModuleParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//ModuleItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" upperBound="-1" eType="#//Step"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ins" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Param" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralParam" eSuperTypes="#//Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefParam" eSuperTypes="#//Param">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//QualifiedID"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
