<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emodel" nsURI="http://emodel/1.0" nsPrefix="emodel">
  <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="../../hu.modembed.model/model/modembedmodel.ecore#//core/Package ../../hu.modembed.model/model/modembedmodel.ecore#//core/NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="../../hu.modembed.model/model/modembedmodel.ecore#//core/PackagedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//types/TypeDefinition" containment="true"/>
  </eClassifiers>
  <eSubpackages name="types">
    <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeDefinition" abstract="true"
        eSuperTypes="#//types/TypeDefinition"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeTypeDefinition" abstract="true"
        eSuperTypes="#//types/TypeDefinition"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnsignedTypeDefinition" eSuperTypes="#//types/PrimitiveTypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceTypeDefinition" eSuperTypes="#//types/CompositeTypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PointerTypeDefinition" eSuperTypes="#//types/CompositeTypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pointerType" lowerBound="1"
          eType="#//types/TypeDefinition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayDefinition" eSuperTypes="#//types/CompositeTypeDefinition"/>
    <eClassifiers xsi:type="ecore:EClass" name="StructureTypeDefinition" eSuperTypes="#//types/CompositeTypeDefinition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//types/StructureTypeElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructureTypeElement" eSuperTypes="../../hu.modembed.model/model/modembedmodel.ecore#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//types/TypeDefinition" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="expressions">
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Instruction"/>
  </eSubpackages>
</ecore:EPackage>
