/*
 * generated by Xtext
 */
package hu.e.parser.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ESyntaxUiModule extends hu.e.parser.ui.AbstractESyntaxUiModule {
	public ESyntaxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return CompilerBuilderParticipant.class;
	}
	
}
