/*
 * generated by Xtext
 */
package hu.e.parser.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ESyntaxUiModule extends hu.e.parser.ui.AbstractESyntaxUiModule {
	public ESyntaxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
