/*
* generated by Xtext
*/
package hu.e.parser.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ESyntaxOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
