<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="01194" edc:modid="lpwr_deep_sleep_sib_v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x2" edc:locsize="0x2" edc:wordimpl="0xffff" edc:wordinit="0x0" edc:wordsafe="0xffff" edc:wordsize="0x2"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="n-------------nc" edc:cname="DSCON" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="u-------------uu" edc:name="DSCON" edc:nzwidth="16" edc:por="0-------------00">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="mode0">
        <edc:SFRFieldDef edc:cname="RELEASE" edc:desc="" edc:mask="0x1" edc:name="RELEASE" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSBOR" edc:desc="" edc:mask="0x1" edc:name="DSBOR" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="13"/>
        <edc:SFRFieldDef edc:cname="DSEN" edc:desc="" edc:mask="0x1" edc:name="DSEN" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="-------nn--nnn-n" edc:cname="DSWAKE" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="-------uu--uu1-u" edc:name="DSWAKE" edc:nzwidth="16" edc:por="-------00--000-1">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="mode0">
        <edc:SFRFieldDef edc:cname="DSPOR" edc:desc="" edc:mask="0x1" edc:name="POR" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="DSMCLR" edc:desc="" edc:mask="0x1" edc:name="MCLR" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSRTC" edc:desc="" edc:mask="0x1" edc:name="RTCC" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSWDT" edc:desc="" edc:mask="0x1" edc:name="DSWDT" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="2"/>
        <edc:SFRFieldDef edc:cname="DSFLT" edc:desc="" edc:mask="0x1" edc:name="DSFLT" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSINT0" edc:desc="" edc:mask="0x1" edc:name="INT0" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="DSGPR0" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="uuuuuuuuuuuuuuuu" edc:name="DSGPR0" edc:nzwidth="16" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="mode0">
        <edc:SFRFieldDef edc:cname="DSGPR0" edc:desc="" edc:mask="0x1" edc:name="DSGPR0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR1" edc:desc="" edc:mask="0x1" edc:name="DSGPR1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR2" edc:desc="" edc:mask="0x1" edc:name="DSGPR2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR3" edc:desc="" edc:mask="0x1" edc:name="DSGPR3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR4" edc:desc="" edc:mask="0x1" edc:name="DSGPR4" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR5" edc:desc="" edc:mask="0x1" edc:name="DSGPR5" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR6" edc:desc="" edc:mask="0x1" edc:name="DSGPR6" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR7" edc:desc="" edc:mask="0x1" edc:name="DSGPR7" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR8" edc:desc="" edc:mask="0x1" edc:name="DSGPR8" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR9" edc:desc="" edc:mask="0x1" edc:name="DSGPR9" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR10" edc:desc="" edc:mask="0x1" edc:name="DSGPR10" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR11" edc:desc="" edc:mask="0x1" edc:name="DSGPR11" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR12" edc:desc="" edc:mask="0x1" edc:name="DSGPR12" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR13" edc:desc="" edc:mask="0x1" edc:name="DSGPR13" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR14" edc:desc="" edc:mask="0x1" edc:name="DSGPR14" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR15" edc:desc="" edc:mask="0x1" edc:name="DSGPR15" edc:nzwidth="1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="mode1"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="DSGPR1" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="uuuuuuuuuuuuuuuu" edc:name="DSGPR1" edc:nzwidth="16" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="mode0">
        <edc:SFRFieldDef edc:cname="DSGPR0" edc:desc="" edc:mask="0x1" edc:name="DSGPR0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR1" edc:desc="" edc:mask="0x1" edc:name="DSGPR1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR2" edc:desc="" edc:mask="0x1" edc:name="DSGPR2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR3" edc:desc="" edc:mask="0x1" edc:name="DSGPR3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR4" edc:desc="" edc:mask="0x1" edc:name="DSGPR4" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR5" edc:desc="" edc:mask="0x1" edc:name="DSGPR5" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR6" edc:desc="" edc:mask="0x1" edc:name="DSGPR6" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR7" edc:desc="" edc:mask="0x1" edc:name="DSGPR7" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR8" edc:desc="" edc:mask="0x1" edc:name="DSGPR8" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR9" edc:desc="" edc:mask="0x1" edc:name="DSGPR9" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR10" edc:desc="" edc:mask="0x1" edc:name="DSGPR10" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR11" edc:desc="" edc:mask="0x1" edc:name="DSGPR11" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR12" edc:desc="" edc:mask="0x1" edc:name="DSGPR12" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR13" edc:desc="" edc:mask="0x1" edc:name="DSGPR13" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR14" edc:desc="" edc:mask="0x1" edc:name="DSGPR14" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DSGPR15" edc:desc="" edc:mask="0x1" edc:name="DSGPR15" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
</edc:Module>