<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="00774_i2c_pb_v1" edc:modid="i2c_pb_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x4" edc:locsize="0x4" edc:wordimpl="0xffffffff" edc:wordinit="0x0" edc:wordsafe="0xffffffff" edc:wordsize="0x4"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="----------------n-nnnnnnnnnnnnnn" edc:cname="I2C@CON" edc:desc="" edc:grp="I2C" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------0001000000000000" edc:name="I2C@CON" edc:nzwidth="0x20" edc:por="----------------0001000000000000" edc:portals="CLR SET INV">
    <edc:AliasList>
      <edc:LegacyAlias edc:cname="I2C%x%%y%CON"/>
    </edc:AliasList>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="SEN" edc:desc="" edc:mask="0x1" edc:name="SEN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RSEN" edc:desc="" edc:mask="0x1" edc:name="RSEN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="PEN" edc:desc="" edc:mask="0x1" edc:name="PEN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RCEN" edc:desc="" edc:mask="0x1" edc:name="RCEN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="ACKEN" edc:desc="" edc:mask="0x1" edc:name="ACKEN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="ACKDT" edc:desc="" edc:mask="0x1" edc:name="ACKDT" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="STREN" edc:desc="" edc:mask="0x1" edc:name="STREN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="GCEN" edc:desc="" edc:mask="0x1" edc:name="GCEN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SMEN" edc:desc="" edc:mask="0x1" edc:name="SMEN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="DISSLW" edc:desc="" edc:mask="0x1" edc:name="DISSLW" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="A10M" edc:desc="" edc:mask="0x1" edc:name="A10M" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="STRICT" edc:desc="" edc:mask="0x1" edc:name="STRICT" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SCLREL" edc:desc="" edc:mask="0x1" edc:name="SCLREL" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SIDL" edc:desc="" edc:mask="0x1" edc:name="SIDL" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FRZ" edc:desc="" edc:ishidden="true" edc:islanghidden="true" edc:mask="0x1" edc:name="FRZ" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="ON" edc:desc="" edc:mask="0x1" edc:name="ON" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:AdjustPoint edc:offset="0xb"/>
        <edc:SFRFieldDef edc:cname="IPMIEN" edc:desc="" edc:mask="0x1" edc:name="IPMIEN" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="0x1"/>
        <edc:SFRFieldDef edc:cname="I2CSIDL" edc:desc="" edc:mask="0x1" edc:name="I2CSIDL" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="0x1"/>
        <edc:SFRFieldDef edc:cname="I2CEN" edc:desc="" edc:mask="0x1" edc:name="I2CEN" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.1">
        <edc:SFRFieldDef edc:cname="w" edc:desc="" edc:mask="0x1" edc:name="w" edc:nzwidth="0x20"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:FreezeBit edc:freezeval="1" edc:name="I2C@" edc:pos="14"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------rr---crrccrccrrr" edc:cname="I2C@STAT" edc:desc="" edc:grp="I2C" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------00---00000000000" edc:name="I2C@STAT" edc:nzwidth="0x20" edc:por="----------------00---00000000000" edc:portals="CLR SET INV">
    <edc:AliasList>
      <edc:LegacyAlias edc:cname="I2C%x%%y%STAT"/>
    </edc:AliasList>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="TBF" edc:desc="" edc:mask="0x1" edc:name="TBF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RBF" edc:desc="" edc:mask="0x1" edc:name="RBF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="R_W" edc:desc="" edc:mask="0x1" edc:name="RW" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="S" edc:desc="" edc:mask="0x1" edc:name="S" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="P" edc:desc="" edc:mask="0x1" edc:name="P" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="D_A" edc:desc="" edc:mask="0x1" edc:name="DA" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="I2COV" edc:desc="" edc:mask="0x1" edc:name="I2COV" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="IWCOL" edc:desc="" edc:mask="0x1" edc:name="IWCOL" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="ADD10" edc:desc="" edc:mask="0x1" edc:name="ADD10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="GCSTAT" edc:desc="" edc:mask="0x1" edc:name="GCSTAT" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="BCL" edc:desc="" edc:mask="0x1" edc:name="BCL" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="TRSTAT" edc:desc="" edc:mask="0x1" edc:name="TRSTAT" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="ACKSTAT" edc:desc="" edc:mask="0x1" edc:name="ACKSTAT" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:AdjustPoint edc:offset="0x6"/>
        <edc:SFRFieldDef edc:cname="I2CPOV" edc:desc="" edc:mask="0x1" edc:name="I2CPOV" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.1">
        <edc:SFRFieldDef edc:cname="w" edc:desc="" edc:mask="0x1" edc:name="w" edc:nzwidth="0x20"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------------nnnnnnnnnn" edc:cname="I2C@ADD" edc:desc="" edc:grp="I2C" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------------0000000000" edc:name="I2C@ADD" edc:nzwidth="0x20" edc:por="----------------------0000000000" edc:portals="CLR SET INV">
    <edc:AliasList>
      <edc:LegacyAlias edc:cname="I2C%x%%y%ADD"/>
    </edc:AliasList>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="I2CADD" edc:desc="" edc:islanghidden="true" edc:mask="0x3ff" edc:name="I2CADD" edc:nzwidth="0xa"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------------nnnnnnnnnn" edc:cname="I2C@MSK" edc:desc="" edc:grp="I2C" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------------0000000000" edc:name="I2C@MSK" edc:nzwidth="0x20" edc:por="----------------------0000000000" edc:portals="CLR SET INV">
    <edc:AliasList>
      <edc:LegacyAlias edc:cname="I2C%x%%y%MSK"/>
    </edc:AliasList>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="I2CMSK" edc:desc="" edc:islanghidden="true" edc:mask="0x3ff" edc:name="I2CMSK" edc:nzwidth="0xa"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="--------------------nnnnnnnnnnnn" edc:cname="I2C@BRG" edc:desc="" edc:grp="I2C" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="--------------------000000000000" edc:name="I2C@BRG" edc:nzwidth="0x20" edc:por="--------------------000000000000" edc:portals="CLR SET INV">
    <edc:AliasList>
      <edc:LegacyAlias edc:cname="I2C%x%%y%BRG"/>
    </edc:AliasList>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="I2CBRG" edc:desc="" edc:islanghidden="true" edc:mask="0xfff" edc:name="I2CBRG" edc:nzwidth="0xc"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="------------------------nnnnnnnn" edc:cname="I2C@TRN" edc:desc="" edc:grp="I2C" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="------------------------00000000" edc:name="I2C@TRN" edc:nzwidth="0x20" edc:por="------------------------00000000" edc:portals="CLR SET INV">
    <edc:AliasList>
      <edc:LegacyAlias edc:cname="I2C%x%%y%TRN"/>
    </edc:AliasList>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="I2CTRN" edc:desc="" edc:islanghidden="true" edc:mask="0xff" edc:name="I2CTRN" edc:nzwidth="0x8"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="------------------------nnnnnnnn" edc:cname="I2C@RCV" edc:desc="" edc:grp="I2C" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="------------------------00000000" edc:name="I2C@RCV" edc:nzwidth="0x20" edc:por="------------------------00000000" edc:portals="- - -">
    <edc:AliasList>
      <edc:LegacyAlias edc:cname="I2C%x%%y%RCV"/>
    </edc:AliasList>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="I2CRCV" edc:desc="" edc:islanghidden="true" edc:mask="0xff" edc:name="I2CRCV" edc:nzwidth="0x8"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
</edc:Module>