<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="00800_dac_4bit_ctrl_pb_v1" edc:modid="dac_4bit_ctrl_pb_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x4" edc:locsize="0x4" edc:wordimpl="0xffffffff" edc:wordinit="0x0" edc:wordsafe="0xffffffff" edc:wordsize="0x4"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="----------------n----nnn-nnnnnnn" edc:cname="CVRCON" edc:desc="" edc:grp="DAC4" edc:impl="0xffffffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="00000000000000000000000100000000" edc:name="CVRCON" edc:nzwidth="0x20" edc:por="00000000000000000000000100000000" edc:portals="CLR SET INV">
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="CVR" edc:desc="" edc:mask="0xf" edc:name="CVR" edc:nzwidth="0x4"/>
        <edc:SFRFieldDef edc:cname="CVRSS" edc:desc="" edc:mask="0x1" edc:name="CVRSS" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="CVRR" edc:desc="" edc:mask="0x1" edc:name="CVRR" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="CVROE" edc:desc="" edc:mask="0x1" edc:name="CVROE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="BGSEL" edc:desc="" edc:mask="0x3" edc:name="BGSEL" edc:nzwidth="2"/>
        <edc:SFRFieldDef edc:cname="VREFSEL" edc:desc="" edc:mask="0x1" edc:name="VREFSEL" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="ON" edc:desc="" edc:mask="0x1" edc:name="ON" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="CVR0" edc:desc="" edc:mask="0x1" edc:name="CVR0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="CVR1" edc:desc="" edc:mask="0x1" edc:name="CVR1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="CVR2" edc:desc="" edc:mask="0x1" edc:name="CVR2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="CVR3" edc:desc="" edc:mask="0x1" edc:name="CVR3" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="BGSEL0" edc:desc="" edc:mask="0x1" edc:name="BGSEL0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="BGSEL1" edc:desc="" edc:mask="0x1" edc:name="BGSEL1" edc:nzwidth="1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.1">
        <edc:SFRFieldDef edc:cname="w" edc:desc="" edc:mask="0x1" edc:name="w" edc:nzwidth="0x20"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
</edc:Module>