<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="01198" edc:modid="can_enh16_v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x2" edc:locsize="0x2" edc:wordimpl="0xffff" edc:wordinit="0x0" edc:wordsafe="0xffff" edc:wordsize="0x2"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="--nnnnnnrrr-n--n" edc:cname="C@CTRL1" edc:desc="" edc:impl="0x3fe9" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000x10010000000" edc:name="C@CTRL1" edc:nzwidth="0x10" edc:por="0000x10010000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="WIN" edc:desc="" edc:mask="0x1" edc:name="WIN" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="2"/>
        <edc:SFRFieldDef edc:cname="CANCAP" edc:desc="" edc:mask="0x1" edc:name="CANCAP" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="OPMODE" edc:desc="" edc:mask="0x7" edc:name="OPMODE" edc:nzwidth="0x3"/>
        <edc:SFRFieldDef edc:cname="REQOP" edc:desc="" edc:mask="0x7" edc:name="REQOP" edc:nzwidth="0x3"/>
        <edc:SFRFieldDef edc:cname="CANCKS" edc:desc="" edc:mask="0x1" edc:name="CANCKS" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="ABAT" edc:desc="" edc:mask="0x1" edc:name="ABAT" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="CSIDL" edc:desc="" edc:mask="0x1" edc:name="CSIDL" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:AdjustPoint edc:offset="5"/>
        <edc:SFRFieldDef edc:cname="OPMODE0" edc:desc="" edc:mask="0x1" edc:name="OPMODE0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OPMODE1" edc:desc="" edc:mask="0x1" edc:name="OPMODE1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OPMODE2" edc:desc="" edc:mask="0x1" edc:name="OPMODE2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="REQOP0" edc:desc="" edc:mask="0x1" edc:name="REQOP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="REQOP1" edc:desc="" edc:mask="0x1" edc:name="REQOP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="REQOP2" edc:desc="" edc:mask="0x1" edc:name="REQOP2" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="-----------rrrrr" edc:cname="C@CTRL2" edc:desc="" edc:impl="0x1f" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@CTRL2" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="DNCNT" edc:desc="" edc:mask="0x1f" edc:name="DNCNT" edc:nzwidth="0x5"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="DNCNT0" edc:desc="" edc:mask="0x1" edc:name="DNCNT0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DNCNT1" edc:desc="" edc:mask="0x1" edc:name="DNCNT1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DNCNT2" edc:desc="" edc:mask="0x1" edc:name="DNCNT2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DNCNT3" edc:desc="" edc:mask="0x1" edc:name="DNCNT3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DNCNT4" edc:desc="" edc:mask="0x1" edc:name="DNCNT4" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="---rrrrr-rrrrrrr" edc:cname="C@VEC" edc:desc="" edc:impl="0x1f7f" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000001000000" edc:name="C@VEC" edc:nzwidth="0x10" edc:por="0000000001000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="ICODE" edc:desc="" edc:mask="0x7f" edc:name="ICODE" edc:nzwidth="0x7"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="FILHIT" edc:desc="" edc:mask="0x1f" edc:name="FILHIT" edc:nzwidth="0x5"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="ICODE0" edc:desc="" edc:mask="0x1" edc:name="ICODE0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="ICODE1" edc:desc="" edc:mask="0x1" edc:name="ICODE1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="ICODE2" edc:desc="" edc:mask="0x1" edc:name="ICODE2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="ICODE3" edc:desc="" edc:mask="0x1" edc:name="ICODE3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="ICODE4" edc:desc="" edc:mask="0x1" edc:name="ICODE4" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="ICODE5" edc:desc="" edc:mask="0x1" edc:name="ICODE5" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="ICODE6" edc:desc="" edc:mask="0x1" edc:name="ICODE6" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="FILHIT0" edc:desc="" edc:mask="0x1" edc:name="FILHIT0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FILHIT1" edc:desc="" edc:mask="0x1" edc:name="FILHIT1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FILHIT2" edc:desc="" edc:mask="0x1" edc:name="FILHIT2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FILHIT3" edc:desc="" edc:mask="0x1" edc:name="FILHIT3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FILHIT4" edc:desc="" edc:mask="0x1" edc:name="FILHIT4" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnn--------nnnnn" edc:cname="C@FCTRL" edc:desc="" edc:impl="0xe01f" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@FCTRL" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="FSA" edc:desc="" edc:mask="0x1f" edc:name="FSA" edc:nzwidth="0x5"/>
        <edc:AdjustPoint edc:offset="8"/>
        <edc:SFRFieldDef edc:cname="DMABS" edc:desc="" edc:mask="0x7" edc:name="DMABS" edc:nzwidth="0x3"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="FSA0" edc:desc="" edc:mask="0x1" edc:name="FSA0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FSA1" edc:desc="" edc:mask="0x1" edc:name="FSA1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FSA2" edc:desc="" edc:mask="0x1" edc:name="FSA2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FSA3" edc:desc="" edc:mask="0x1" edc:name="FSA3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FSA4" edc:desc="" edc:mask="0x1" edc:name="FSA4" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="8"/>
        <edc:SFRFieldDef edc:cname="DMABS0" edc:desc="" edc:mask="0x1" edc:name="DMABS0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMABS1" edc:desc="" edc:mask="0x1" edc:name="DMABS1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMABS2" edc:desc="" edc:mask="0x1" edc:name="DMABS2" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="--rrrrrr--rrrrrr" edc:cname="C@FIFO" edc:desc="" edc:impl="0x3f3f" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@FIFO" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="FNRB" edc:desc="" edc:mask="0x3f" edc:name="FNRB" edc:nzwidth="0x6"/>
        <edc:AdjustPoint edc:offset="2"/>
        <edc:SFRFieldDef edc:cname="FBP" edc:desc="" edc:mask="0x3f" edc:name="FBP" edc:nzwidth="0x6"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="FNRB0" edc:desc="" edc:mask="0x1" edc:name="FNRB0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FNRB1" edc:desc="" edc:mask="0x1" edc:name="FNRB1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FNRB2" edc:desc="" edc:mask="0x1" edc:name="FNRB2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FNRB3" edc:desc="" edc:mask="0x1" edc:name="FNRB3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FNRB4" edc:desc="" edc:mask="0x1" edc:name="FNRB4" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FNRB5" edc:desc="" edc:mask="0x1" edc:name="FNRB5" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="2"/>
        <edc:SFRFieldDef edc:cname="FBP0" edc:desc="" edc:mask="0x1" edc:name="FBP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FBP1" edc:desc="" edc:mask="0x1" edc:name="FBP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FBP2" edc:desc="" edc:mask="0x1" edc:name="FBP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FBP3" edc:desc="" edc:mask="0x1" edc:name="FBP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FBP4" edc:desc="" edc:mask="0x1" edc:name="FBP4" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="FBP5" edc:desc="" edc:mask="0x1" edc:name="FBP5" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="--rrrrrrccc-cccc" edc:cname="C@INTF" edc:desc="" edc:impl="0x3fef" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@INTF" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="TBIF" edc:desc="" edc:mask="0x1" edc:name="TBIF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RBIF" edc:desc="" edc:mask="0x1" edc:name="RBIF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RBOVIF" edc:desc="" edc:mask="0x1" edc:name="RBOVIF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FIFOIF" edc:desc="" edc:mask="0x1" edc:name="FIFOIF" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="ERRIF" edc:desc="" edc:mask="0x1" edc:name="ERRIF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="WAKIF" edc:desc="" edc:mask="0x1" edc:name="WAKIF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="IVRIF" edc:desc="" edc:mask="0x1" edc:name="IVRIF" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EWARN" edc:desc="" edc:mask="0x1" edc:name="EWARN" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXWAR" edc:desc="" edc:mask="0x1" edc:name="RXWAR" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="TXWAR" edc:desc="" edc:mask="0x1" edc:name="TXWAR" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXBP" edc:desc="" edc:mask="0x1" edc:name="RXBP" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="TXBP" edc:desc="" edc:mask="0x1" edc:name="TXBP" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="TXBO" edc:desc="" edc:mask="0x1" edc:name="TXBO" edc:nzwidth="0x1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="--------nnnnnnnn" edc:cname="C@INTE" edc:desc="" edc:impl="0xff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@INTE" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="TBIE" edc:desc="" edc:mask="0x1" edc:name="TBIE" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RBIE" edc:desc="" edc:mask="0x1" edc:name="RBIE" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RBOVIE" edc:desc="" edc:mask="0x1" edc:name="RBOVIE" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FIFOIE" edc:desc="" edc:mask="0x1" edc:name="FIFOIE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="ERRIE" edc:desc="" edc:mask="0x1" edc:name="ERRIE" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="WAKIE" edc:desc="" edc:mask="0x1" edc:name="WAKIE" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="IVRIE" edc:desc="" edc:mask="0x1" edc:name="IVRIE" edc:nzwidth="0x1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@EC" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@EC" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="RERRCNT" edc:desc="" edc:mask="0xff" edc:name="RERRCNT" edc:nzwidth="0x8"/>
        <edc:SFRFieldDef edc:cname="TERRCNT" edc:desc="" edc:mask="0xff" edc:name="TERRCNT" edc:nzwidth="0x8"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="--------nnnnnnnn" edc:cname="C@CFG1" edc:desc="" edc:impl="0xff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@CFG1" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="BRP" edc:desc="" edc:mask="0x3f" edc:name="BRP" edc:nzwidth="0x6"/>
        <edc:SFRFieldDef edc:cname="SJW" edc:desc="" edc:mask="0x3" edc:name="SJW" edc:nzwidth="0x2"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="BRP0" edc:desc="" edc:mask="0x1" edc:name="BRP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="BRP1" edc:desc="" edc:mask="0x1" edc:name="BRP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="BRP2" edc:desc="" edc:mask="0x1" edc:name="BRP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="BRP3" edc:desc="" edc:mask="0x1" edc:name="BRP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="BRP4" edc:desc="" edc:mask="0x1" edc:name="BRP4" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="BRP5" edc:desc="" edc:mask="0x1" edc:name="BRP5" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SJW0" edc:desc="" edc:mask="0x1" edc:name="SJW0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SJW1" edc:desc="" edc:mask="0x1" edc:name="SJW1" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="-n---nnnnnnnnnnn" edc:cname="C@CFG2" edc:desc="" edc:impl="0x47ff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="-0---00000000000" edc:name="C@CFG2" edc:nzwidth="0x10" edc:por="-0---00000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="PRSEG" edc:desc="" edc:mask="0x7" edc:name="PRSEG" edc:nzwidth="0x3"/>
        <edc:SFRFieldDef edc:cname="SEG1PH" edc:desc="" edc:mask="0x7" edc:name="SEG1PH" edc:nzwidth="0x3"/>
        <edc:SFRFieldDef edc:cname="SAM" edc:desc="" edc:mask="0x1" edc:name="SAM" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SEG2PHTS" edc:desc="" edc:mask="0x1" edc:name="SEG2PHTS" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SEG2PH" edc:desc="" edc:mask="0x7" edc:name="SEG2PH" edc:nzwidth="0x3"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="WAKFIL" edc:desc="" edc:mask="0x1" edc:name="WAKFIL" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="PRSEG0" edc:desc="" edc:mask="0x1" edc:name="PRSEG0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PRSEG1" edc:desc="" edc:mask="0x1" edc:name="PRSEG1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PRSEG2" edc:desc="" edc:mask="0x1" edc:name="PRSEG2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SEG1PH0" edc:desc="" edc:mask="0x1" edc:name="SEG1PH0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SEG1PH1" edc:desc="" edc:mask="0x1" edc:name="SEG1PH1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SEG1PH2" edc:desc="" edc:mask="0x1" edc:name="SEG1PH2" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="2"/>
        <edc:SFRFieldDef edc:cname="SEG2PH0" edc:desc="" edc:mask="0x1" edc:name="SEG2PH0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SEG2PH1" edc:desc="" edc:mask="0x1" edc:name="SEG2PH1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SEG2PH2" edc:desc="" edc:mask="0x1" edc:name="SEG2PH2" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@FEN1" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000111111" edc:name="C@FEN1" edc:nzwidth="0x10" edc:por="0000000000111111">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="FLTEN0" edc:desc="" edc:mask="0x1" edc:name="FLTEN0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN1" edc:desc="" edc:mask="0x1" edc:name="FLTEN1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN2" edc:desc="" edc:mask="0x1" edc:name="FLTEN2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN3" edc:desc="" edc:mask="0x1" edc:name="FLTEN3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN4" edc:desc="" edc:mask="0x1" edc:name="FLTEN4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN5" edc:desc="" edc:mask="0x1" edc:name="FLTEN5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN6" edc:desc="" edc:mask="0x1" edc:name="FLTEN6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN7" edc:desc="" edc:mask="0x1" edc:name="FLTEN7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN8" edc:desc="" edc:mask="0x1" edc:name="FLTEN8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN9" edc:desc="" edc:mask="0x1" edc:name="FLTEN9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN10" edc:desc="" edc:mask="0x1" edc:name="FLTEN10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN11" edc:desc="" edc:mask="0x1" edc:name="FLTEN11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN12" edc:desc="" edc:mask="0x1" edc:name="FLTEN12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN13" edc:desc="" edc:mask="0x1" edc:name="FLTEN13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN14" edc:desc="" edc:mask="0x1" edc:name="FLTEN14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="FLTEN15" edc:desc="" edc:mask="0x1" edc:name="FLTEN15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------" edc:cname="RESERVED1" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------" edc:name="RESERVED1" edc:nzwidth="16" edc:por="----------------">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@FMSKSEL1" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@FMSKSEL1" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="F0MSK" edc:desc="" edc:mask="0x3" edc:name="F0MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F1MSK" edc:desc="" edc:mask="0x3" edc:name="F1MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F2MSK" edc:desc="" edc:mask="0x3" edc:name="F2MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F3MSK" edc:desc="" edc:mask="0x3" edc:name="F3MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F4MSK" edc:desc="" edc:mask="0x3" edc:name="F4MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F5MSK" edc:desc="" edc:mask="0x3" edc:name="F5MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F6MSK" edc:desc="" edc:mask="0x3" edc:name="F6MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F7MSK" edc:desc="" edc:mask="0x3" edc:name="F7MSK" edc:nzwidth="0x2"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="F0MSK0" edc:desc="" edc:mask="0x1" edc:name="F0MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F0MSK1" edc:desc="" edc:mask="0x1" edc:name="F0MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F1MSK0" edc:desc="" edc:mask="0x1" edc:name="F1MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F1MSK1" edc:desc="" edc:mask="0x1" edc:name="F1MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F2MSK0" edc:desc="" edc:mask="0x1" edc:name="F2MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F2MSK1" edc:desc="" edc:mask="0x1" edc:name="F2MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F3MSK0" edc:desc="" edc:mask="0x1" edc:name="F3MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F3MSK1" edc:desc="" edc:mask="0x1" edc:name="F3MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F4MSK0" edc:desc="" edc:mask="0x1" edc:name="F4MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F4MSK1" edc:desc="" edc:mask="0x1" edc:name="F4MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F5MSK0" edc:desc="" edc:mask="0x1" edc:name="F5MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F5MSK1" edc:desc="" edc:mask="0x1" edc:name="F5MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F6MSK0" edc:desc="" edc:mask="0x1" edc:name="F6MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F6MSK1" edc:desc="" edc:mask="0x1" edc:name="F6MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F7MSK0" edc:desc="" edc:mask="0x1" edc:name="F7MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F7MSK1" edc:desc="" edc:mask="0x1" edc:name="F7MSK1" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@FMSKSEL2" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@FMSKSEL2" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="F8MSK" edc:desc="" edc:mask="0x3" edc:name="F8MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F9MSK" edc:desc="" edc:mask="0x3" edc:name="F9MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F10MSK" edc:desc="" edc:mask="0x3" edc:name="F10MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F11MSK" edc:desc="" edc:mask="0x3" edc:name="F11MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F12MSK" edc:desc="" edc:mask="0x3" edc:name="F12MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F13MSK" edc:desc="" edc:mask="0x3" edc:name="F13MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F14MSK" edc:desc="" edc:mask="0x3" edc:name="F14MSK" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="F15MSK" edc:desc="" edc:mask="0x3" edc:name="F15MSK" edc:nzwidth="0x2"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="F8MSK0" edc:desc="" edc:mask="0x1" edc:name="F8MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F8MSK1" edc:desc="" edc:mask="0x1" edc:name="F8MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F9MSK0" edc:desc="" edc:mask="0x1" edc:name="F9MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F9MSK1" edc:desc="" edc:mask="0x1" edc:name="F9MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F10MSK0" edc:desc="" edc:mask="0x1" edc:name="F10MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F10MSK1" edc:desc="" edc:mask="0x1" edc:name="F10MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F11MSK0" edc:desc="" edc:mask="0x1" edc:name="F11MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F11MSK1" edc:desc="" edc:mask="0x1" edc:name="F11MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F12MSK0" edc:desc="" edc:mask="0x1" edc:name="F12MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F12MSK1" edc:desc="" edc:mask="0x1" edc:name="F12MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F13MSK0" edc:desc="" edc:mask="0x1" edc:name="F13MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F13MSK1" edc:desc="" edc:mask="0x1" edc:name="F13MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F14MSK0" edc:desc="" edc:mask="0x1" edc:name="F14MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F14MSK1" edc:desc="" edc:mask="0x1" edc:name="F14MSK1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F15MSK0" edc:desc="" edc:mask="0x1" edc:name="F15MSK0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F15MSK1" edc:desc="" edc:mask="0x1" edc:name="F15MSK1" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------" edc:cname="RESERVED2" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------" edc:name="RESERVED2" edc:nzwidth="16" edc:por="----------------">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------" edc:cname="RESERVED3" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------" edc:name="RESERVED3" edc:nzwidth="16" edc:por="----------------">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@BUFPNT1" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@BUFPNT1" edc:nmmrid="0x0" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="F0BP" edc:desc="" edc:mask="0xf" edc:name="F0BP" edc:nzwidth="0x4"/>
            <edc:SFRFieldDef edc:cname="F1BP" edc:desc="" edc:mask="0xf" edc:name="F1BP" edc:nzwidth="0x4"/>
            <edc:SFRFieldDef edc:cname="F2BP" edc:desc="" edc:mask="0xf" edc:name="F2BP" edc:nzwidth="0x4"/>
            <edc:SFRFieldDef edc:cname="F3BP" edc:desc="" edc:mask="0xf" edc:name="F3BP" edc:nzwidth="0x4"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="F0BP0" edc:desc="" edc:mask="0x1" edc:name="F0BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F0BP1" edc:desc="" edc:mask="0x1" edc:name="F0BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F0BP2" edc:desc="" edc:mask="0x1" edc:name="F0BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F0BP3" edc:desc="" edc:mask="0x1" edc:name="F0BP3" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F1BP0" edc:desc="" edc:mask="0x1" edc:name="F1BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F1BP1" edc:desc="" edc:mask="0x1" edc:name="F1BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F1BP2" edc:desc="" edc:mask="0x1" edc:name="F1BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F1BP3" edc:desc="" edc:mask="0x1" edc:name="F1BP3" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F2BP0" edc:desc="" edc:mask="0x1" edc:name="F2BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F2BP1" edc:desc="" edc:mask="0x1" edc:name="F2BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F2BP2" edc:desc="" edc:mask="0x1" edc:name="F2BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F2BP3" edc:desc="" edc:mask="0x1" edc:name="F2BP3" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F3BP0" edc:desc="" edc:mask="0x1" edc:name="F3BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F3BP1" edc:desc="" edc:mask="0x1" edc:name="F3BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F3BP2" edc:desc="" edc:mask="0x1" edc:name="F3BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F3BP3" edc:desc="" edc:mask="0x1" edc:name="F3BP3" edc:nzwidth="1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="cccccccccccccccc" edc:cname="C@RXFUL1" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@RXFUL1" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="RXFUL0" edc:desc="" edc:mask="0x1" edc:name="RXFUL0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL1" edc:desc="" edc:mask="0x1" edc:name="RXFUL1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL2" edc:desc="" edc:mask="0x1" edc:name="RXFUL2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL3" edc:desc="" edc:mask="0x1" edc:name="RXFUL3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL4" edc:desc="" edc:mask="0x1" edc:name="RXFUL4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL5" edc:desc="" edc:mask="0x1" edc:name="RXFUL5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL6" edc:desc="" edc:mask="0x1" edc:name="RXFUL6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL7" edc:desc="" edc:mask="0x1" edc:name="RXFUL7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL8" edc:desc="" edc:mask="0x1" edc:name="RXFUL8" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL9" edc:desc="" edc:mask="0x1" edc:name="RXFUL9" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL10" edc:desc="" edc:mask="0x1" edc:name="RXFUL10" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL11" edc:desc="" edc:mask="0x1" edc:name="RXFUL11" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL12" edc:desc="" edc:mask="0x1" edc:name="RXFUL12" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL13" edc:desc="" edc:mask="0x1" edc:name="RXFUL13" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL14" edc:desc="" edc:mask="0x1" edc:name="RXFUL14" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL15" edc:desc="" edc:mask="0x1" edc:name="RXFUL15" edc:nzwidth="0x1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
        <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@BUFPNT2" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@BUFPNT2" edc:nmmrid="0x2" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="F4BP" edc:desc="" edc:mask="0xf" edc:name="F4BP" edc:nzwidth="0x4"/>
            <edc:SFRFieldDef edc:cname="F5BP" edc:desc="" edc:mask="0xf" edc:name="F5BP" edc:nzwidth="0x4"/>
            <edc:SFRFieldDef edc:cname="F6BP" edc:desc="" edc:mask="0xf" edc:name="F6BP" edc:nzwidth="0x4"/>
            <edc:SFRFieldDef edc:cname="F7BP" edc:desc="" edc:mask="0xf" edc:name="F7BP" edc:nzwidth="0x4"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="F4BP0" edc:desc="" edc:mask="0x1" edc:name="F4BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F4BP1" edc:desc="" edc:mask="0x1" edc:name="F4BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F4BP2" edc:desc="" edc:mask="0x1" edc:name="F4BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F4BP3" edc:desc="" edc:mask="0x1" edc:name="F4BP3" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F5BP0" edc:desc="" edc:mask="0x1" edc:name="F5BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F5BP1" edc:desc="" edc:mask="0x1" edc:name="F5BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F5BP2" edc:desc="" edc:mask="0x1" edc:name="F5BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F5BP3" edc:desc="" edc:mask="0x1" edc:name="F5BP3" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F6BP0" edc:desc="" edc:mask="0x1" edc:name="F6BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F6BP1" edc:desc="" edc:mask="0x1" edc:name="F6BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F6BP2" edc:desc="" edc:mask="0x1" edc:name="F6BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F6BP3" edc:desc="" edc:mask="0x1" edc:name="F6BP3" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F7BP0" edc:desc="" edc:mask="0x1" edc:name="F7BP0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F7BP1" edc:desc="" edc:mask="0x1" edc:name="F7BP1" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F7BP2" edc:desc="" edc:mask="0x1" edc:name="F7BP2" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="F7BP3" edc:desc="" edc:mask="0x1" edc:name="F7BP3" edc:nzwidth="1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="cccccccccccccccc" edc:cname="C@RXFUL2" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@RXFUL2" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="RXFUL16" edc:desc="" edc:mask="0x1" edc:name="RXFUL16" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL17" edc:desc="" edc:mask="0x1" edc:name="RXFUL17" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL18" edc:desc="" edc:mask="0x1" edc:name="RXFUL18" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL19" edc:desc="" edc:mask="0x1" edc:name="RXFUL19" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL20" edc:desc="" edc:mask="0x1" edc:name="RXFUL20" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL21" edc:desc="" edc:mask="0x1" edc:name="RXFUL21" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL22" edc:desc="" edc:mask="0x1" edc:name="RXFUL22" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL23" edc:desc="" edc:mask="0x1" edc:name="RXFUL23" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL24" edc:desc="" edc:mask="0x1" edc:name="RXFUL24" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL25" edc:desc="" edc:mask="0x1" edc:name="RXFUL25" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL26" edc:desc="" edc:mask="0x1" edc:name="RXFUL26" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL27" edc:desc="" edc:mask="0x1" edc:name="RXFUL27" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL28" edc:desc="" edc:mask="0x1" edc:name="RXFUL28" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL29" edc:desc="" edc:mask="0x1" edc:name="RXFUL29" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL30" edc:desc="" edc:mask="0x1" edc:name="RXFUL30" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="RXFUL31" edc:desc="" edc:mask="0x1" edc:name="RXFUL31" edc:nzwidth="0x1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
        <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@BUFPNT3" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@BUFPNT3" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="F8BP" edc:desc="" edc:mask="0xf" edc:name="F8BP" edc:nzwidth="0x4"/>
        <edc:SFRFieldDef edc:cname="F9BP" edc:desc="" edc:mask="0xf" edc:name="F9BP" edc:nzwidth="0x4"/>
        <edc:SFRFieldDef edc:cname="F10BP" edc:desc="" edc:mask="0xf" edc:name="F10BP" edc:nzwidth="0x4"/>
        <edc:SFRFieldDef edc:cname="F11BP" edc:desc="" edc:mask="0xf" edc:name="F11BP" edc:nzwidth="0x4"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="F8BP0" edc:desc="" edc:mask="0x1" edc:name="F8BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F8BP1" edc:desc="" edc:mask="0x1" edc:name="F8BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F8BP2" edc:desc="" edc:mask="0x1" edc:name="F8BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F8BP3" edc:desc="" edc:mask="0x1" edc:name="F8BP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F9BP0" edc:desc="" edc:mask="0x1" edc:name="F9BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F9BP1" edc:desc="" edc:mask="0x1" edc:name="F9BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F9BP2" edc:desc="" edc:mask="0x1" edc:name="F9BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F9BP3" edc:desc="" edc:mask="0x1" edc:name="F9BP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F10BP0" edc:desc="" edc:mask="0x1" edc:name="F10BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F10BP1" edc:desc="" edc:mask="0x1" edc:name="F10BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F10BP2" edc:desc="" edc:mask="0x1" edc:name="F10BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F10BP3" edc:desc="" edc:mask="0x1" edc:name="F10BP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F11BP0" edc:desc="" edc:mask="0x1" edc:name="F11BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F11BP1" edc:desc="" edc:mask="0x1" edc:name="F11BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F11BP2" edc:desc="" edc:mask="0x1" edc:name="F11BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F11BP3" edc:desc="" edc:mask="0x1" edc:name="F11BP3" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@BUFPNT4" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@BUFPNT4" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="F12BP" edc:desc="" edc:mask="0xf" edc:name="F12BP" edc:nzwidth="0x4"/>
        <edc:SFRFieldDef edc:cname="F13BP" edc:desc="" edc:mask="0xf" edc:name="F13BP" edc:nzwidth="0x4"/>
        <edc:SFRFieldDef edc:cname="F14BP" edc:desc="" edc:mask="0xf" edc:name="F14BP" edc:nzwidth="0x4"/>
        <edc:SFRFieldDef edc:cname="F15BP" edc:desc="" edc:mask="0xf" edc:name="F15BP" edc:nzwidth="0x4"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="F12BP0" edc:desc="" edc:mask="0x1" edc:name="F12BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F12BP1" edc:desc="" edc:mask="0x1" edc:name="F12BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F12BP2" edc:desc="" edc:mask="0x1" edc:name="F12BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F12BP3" edc:desc="" edc:mask="0x1" edc:name="F12BP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F13BP0" edc:desc="" edc:mask="0x1" edc:name="F13BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F13BP1" edc:desc="" edc:mask="0x1" edc:name="F13BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F13BP2" edc:desc="" edc:mask="0x1" edc:name="F13BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F13BP3" edc:desc="" edc:mask="0x1" edc:name="F13BP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F14BP0" edc:desc="" edc:mask="0x1" edc:name="F14BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F14BP1" edc:desc="" edc:mask="0x1" edc:name="F14BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F14BP2" edc:desc="" edc:mask="0x1" edc:name="F14BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F14BP3" edc:desc="" edc:mask="0x1" edc:name="F14BP3" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F15BP0" edc:desc="" edc:mask="0x1" edc:name="F15BP0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F15BP1" edc:desc="" edc:mask="0x1" edc:name="F15BP1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F15BP2" edc:desc="" edc:mask="0x1" edc:name="F15BP2" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="F15BP3" edc:desc="" edc:mask="0x1" edc:name="F15BP3" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="cccccccccccccccc" edc:cname="C@RXOVF1" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@RXOVF1" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="RXOVF0" edc:desc="" edc:mask="0x1" edc:name="RXOVF0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF1" edc:desc="" edc:mask="0x1" edc:name="RXOVF1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF2" edc:desc="" edc:mask="0x1" edc:name="RXOVF2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF3" edc:desc="" edc:mask="0x1" edc:name="RXOVF3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF4" edc:desc="" edc:mask="0x1" edc:name="RXOVF4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF5" edc:desc="" edc:mask="0x1" edc:name="RXOVF5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF6" edc:desc="" edc:mask="0x1" edc:name="RXOVF6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF7" edc:desc="" edc:mask="0x1" edc:name="RXOVF7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF8" edc:desc="" edc:mask="0x1" edc:name="RXOVF8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF9" edc:desc="" edc:mask="0x1" edc:name="RXOVF9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF10" edc:desc="" edc:mask="0x1" edc:name="RXOVF10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF11" edc:desc="" edc:mask="0x1" edc:name="RXOVF11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF12" edc:desc="" edc:mask="0x1" edc:name="RXOVF12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF13" edc:desc="" edc:mask="0x1" edc:name="RXOVF13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF14" edc:desc="" edc:mask="0x1" edc:name="RXOVF14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF15" edc:desc="" edc:mask="0x1" edc:name="RXOVF15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="cccccccccccccccc" edc:cname="C@RXOVF2" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@RXOVF2" edc:nzwidth="0x10" edc:por="0000000000000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="RXOVF16" edc:desc="" edc:mask="0x1" edc:name="RXOVF16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF17" edc:desc="" edc:mask="0x1" edc:name="RXOVF17" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF18" edc:desc="" edc:mask="0x1" edc:name="RXOVF18" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF19" edc:desc="" edc:mask="0x1" edc:name="RXOVF19" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF20" edc:desc="" edc:mask="0x1" edc:name="RXOVF20" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF21" edc:desc="" edc:mask="0x1" edc:name="RXOVF21" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF22" edc:desc="" edc:mask="0x1" edc:name="RXOVF22" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF23" edc:desc="" edc:mask="0x1" edc:name="RXOVF23" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF24" edc:desc="" edc:mask="0x1" edc:name="RXOVF24" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF25" edc:desc="" edc:mask="0x1" edc:name="RXOVF25" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF26" edc:desc="" edc:mask="0x1" edc:name="RXOVF26" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF27" edc:desc="" edc:mask="0x1" edc:name="RXOVF27" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF28" edc:desc="" edc:mask="0x1" edc:name="RXOVF28" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF29" edc:desc="" edc:mask="0x1" edc:name="RXOVF29" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF30" edc:desc="" edc:mask="0x1" edc:name="RXOVF30" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="RXOVF31" edc:desc="" edc:mask="0x1" edc:name="RXOVF31" edc:nzwidth="0x1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------" edc:cname="RESERVED4" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------" edc:name="RESERVED4" edc:nzwidth="16" edc:por="----------------">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------" edc:cname="RESERVED5" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------" edc:name="RESERVED5" edc:nzwidth="16" edc:por="----------------">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXM0SID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXM0SID" edc:nmmrid="0x8" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
            <edc:AdjustPoint edc:offset="1"/>
            <edc:SFRFieldDef edc:cname="MIDE" edc:desc="" edc:mask="0x1" edc:name="MIDE" edc:nzwidth="0x1"/>
            <edc:AdjustPoint edc:offset="1"/>
            <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
            <edc:AdjustPoint edc:offset="3"/>
            <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="nrrrnnnnnrrrnnnn" edc:cname="C@TR01CON" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@TR01CON" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="TX0PRI" edc:desc="" edc:mask="0x3" edc:name="TX0PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN0" edc:desc="" edc:mask="0x1" edc:name="RTREN0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ0" edc:desc="" edc:mask="0x1" edc:name="TXREQ0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR0" edc:desc="" edc:mask="0x1" edc:name="TXERR0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB0" edc:desc="" edc:mask="0x1" edc:name="TXLARB0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT0" edc:desc="" edc:mask="0x1" edc:name="TXABT0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN0" edc:desc="" edc:mask="0x1" edc:name="TXEN0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TX1PRI" edc:desc="" edc:mask="0x3" edc:name="TX1PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN1" edc:desc="" edc:mask="0x1" edc:name="RTREN1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ1" edc:desc="" edc:mask="0x1" edc:name="TXREQ1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR1" edc:desc="" edc:mask="0x1" edc:name="TXERR1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB1" edc:desc="" edc:mask="0x1" edc:name="TXLARB1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT1" edc:desc="" edc:mask="0x1" edc:name="TXABT1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN1" edc:desc="" edc:mask="0x1" edc:name="TXEN1" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="TX0PRI0" edc:desc="" edc:mask="0x1" edc:name="TX0PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX0PRI1" edc:desc="" edc:mask="0x1" edc:name="TX0PRI1" edc:nzwidth="1"/>
            <edc:AdjustPoint edc:offset="6"/>
            <edc:SFRFieldDef edc:cname="TX1PRI0" edc:desc="" edc:mask="0x1" edc:name="TX1PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX1PRI1" edc:desc="" edc:mask="0x1" edc:name="TX1PRI1" edc:nzwidth="1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
        <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXM0EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXM0EID" edc:nmmrid="0xa" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="nrrrnnnnnrrrnnnn" edc:cname="C@TR23CON" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@TR23CON" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="TX2PRI" edc:desc="" edc:mask="0x3" edc:name="TX2PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN2" edc:desc="" edc:mask="0x1" edc:name="RTREN2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ2" edc:desc="" edc:mask="0x1" edc:name="TXREQ2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR2" edc:desc="" edc:mask="0x1" edc:name="TXERR2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB2" edc:desc="" edc:mask="0x1" edc:name="TXLARB2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT2" edc:desc="" edc:mask="0x1" edc:name="TXABT2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN2" edc:desc="" edc:mask="0x1" edc:name="TXEN2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TX3PRI" edc:desc="" edc:mask="0x3" edc:name="TX3PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN3" edc:desc="" edc:mask="0x1" edc:name="RTREN3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ3" edc:desc="" edc:mask="0x1" edc:name="TXREQ3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR3" edc:desc="" edc:mask="0x1" edc:name="TXERR3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB3" edc:desc="" edc:mask="0x1" edc:name="TXLARB3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT3" edc:desc="" edc:mask="0x1" edc:name="TXABT3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN3" edc:desc="" edc:mask="0x1" edc:name="TXEN3" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="TX2PRI0" edc:desc="" edc:mask="0x1" edc:name="TX2PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX2PRI1" edc:desc="" edc:mask="0x1" edc:name="TX2PRI1" edc:nzwidth="1"/>
            <edc:AdjustPoint edc:offset="6"/>
            <edc:SFRFieldDef edc:cname="TX3PRI0" edc:desc="" edc:mask="0x1" edc:name="TX3PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX3PRI1" edc:desc="" edc:mask="0x1" edc:name="TX3PRI1" edc:nzwidth="1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
        <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXM1SID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXM1SID" edc:nmmrid="0xc" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
            <edc:AdjustPoint edc:offset="1"/>
            <edc:SFRFieldDef edc:cname="MIDE" edc:desc="" edc:mask="0x1" edc:name="MIDE" edc:nzwidth="0x1"/>
            <edc:AdjustPoint edc:offset="1"/>
            <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
            <edc:AdjustPoint edc:offset="3"/>
            <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="nrrrnnnnnrrrnnnn" edc:cname="C@TR45CON" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@TR45CON" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="TX4PRI" edc:desc="" edc:mask="0x3" edc:name="TX4PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN4" edc:desc="" edc:mask="0x1" edc:name="RTREN4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ4" edc:desc="" edc:mask="0x1" edc:name="TXREQ4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR4" edc:desc="" edc:mask="0x1" edc:name="TXERR4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB4" edc:desc="" edc:mask="0x1" edc:name="TXLARB4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT4" edc:desc="" edc:mask="0x1" edc:name="TXABT4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN4" edc:desc="" edc:mask="0x1" edc:name="TXEN4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TX5PRI" edc:desc="" edc:mask="0x3" edc:name="TX5PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN5" edc:desc="" edc:mask="0x1" edc:name="RTREN5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ5" edc:desc="" edc:mask="0x1" edc:name="TXREQ5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR5" edc:desc="" edc:mask="0x1" edc:name="TXERR5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB5" edc:desc="" edc:mask="0x1" edc:name="TXLARB5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT5" edc:desc="" edc:mask="0x1" edc:name="TXABT5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN5" edc:desc="" edc:mask="0x1" edc:name="TXEN5" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="TX4PRI0" edc:desc="" edc:mask="0x1" edc:name="TX4PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX4PRI1" edc:desc="" edc:mask="0x1" edc:name="TX4PRI1" edc:nzwidth="1"/>
            <edc:AdjustPoint edc:offset="6"/>
            <edc:SFRFieldDef edc:cname="TX5PRI0" edc:desc="" edc:mask="0x1" edc:name="TX5PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX5PRI1" edc:desc="" edc:mask="0x1" edc:name="TX5PRI1" edc:nzwidth="1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
        <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXM1EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXM1EID" edc:nmmrid="0xe" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="nrrrnnnnnrrrnnnn" edc:cname="C@TR67CON" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000000000000" edc:name="C@TR67CON" edc:nzwidth="0x10" edc:por="0000000000000000">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="TX6PRI" edc:desc="" edc:mask="0x3" edc:name="TX6PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN6" edc:desc="" edc:mask="0x1" edc:name="RTREN6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ6" edc:desc="" edc:mask="0x1" edc:name="TXREQ6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR6" edc:desc="" edc:mask="0x1" edc:name="TXERR6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB6" edc:desc="" edc:mask="0x1" edc:name="TXLARB6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT6" edc:desc="" edc:mask="0x1" edc:name="TXABT6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN6" edc:desc="" edc:mask="0x1" edc:name="TXEN6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TX7PRI" edc:desc="" edc:mask="0x3" edc:name="TX7PRI" edc:nzwidth="0x2"/>
            <edc:SFRFieldDef edc:cname="RTREN7" edc:desc="" edc:mask="0x1" edc:name="RTREN7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXREQ7" edc:desc="" edc:mask="0x1" edc:name="TXREQ7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXERR7" edc:desc="" edc:mask="0x1" edc:name="TXERR7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXLARB7" edc:desc="" edc:mask="0x1" edc:name="TXLARB7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXABT7" edc:desc="" edc:mask="0x1" edc:name="TXABT7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="TXEN7" edc:desc="" edc:mask="0x1" edc:name="TXEN7" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="TX6PRI0" edc:desc="" edc:mask="0x1" edc:name="TX6PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX6PRI1" edc:desc="" edc:mask="0x1" edc:name="TX6PRI1" edc:nzwidth="1"/>
            <edc:AdjustPoint edc:offset="6"/>
            <edc:SFRFieldDef edc:cname="TX7PRI0" edc:desc="" edc:mask="0x1" edc:name="TX7PRI0" edc:nzwidth="1"/>
            <edc:SFRFieldDef edc:cname="TX7PRI1" edc:desc="" edc:mask="0x1" edc:name="TX7PRI1" edc:nzwidth="1"/>
          </edc:SFRMode>
        </edc:SFRModeList>
        <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXM2SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXM2SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="MIDE" edc:desc="" edc:mask="0x1" edc:name="MIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXM2EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXM2EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------" edc:cname="RESERVED6" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------" edc:name="RESERVED6" edc:nzwidth="16" edc:por="----------------">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------------" edc:cname="RESERVED7" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------------" edc:name="RESERVED7" edc:nzwidth="16" edc:por="----------------">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0"/>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF0SID" edc:desc="" edc:dma="r" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF0SID" edc:nmmrid="0x14" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
            <edc:AdjustPoint edc:offset="1"/>
            <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
            <edc:AdjustPoint edc:offset="1"/>
            <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
            <edc:AdjustPoint edc:offset="3"/>
            <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXD" edc:desc="" edc:dma="r" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXD" edc:nzwidth="16" edc:por="xxxxxxxxxxxxxxxx">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="C@RXD" edc:desc="" edc:islanghidden="true" edc:mask="0xffff" edc:name="C@RXD" edc:nzwidth="16"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:MuxedSFRDef edc:nzwidth="0x10">
    <edc:SelectSFR edc:when="($0x0 &amp; 0x1) == 0x1">
      <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF0EID" edc:desc="" edc:dma="w" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF0EID" edc:nmmrid="0x16" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
            <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
          </edc:SFRMode>
          <edc:SFRMode edc:id="LT.0">
            <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
    <edc:SelectSFR>
      <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@TXD" edc:desc="" edc:dma="w" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@TXD" edc:nzwidth="16" edc:por="xxxxxxxxxxxxxxxx">
        <edc:AliasList/>
        <edc:SFRModeList>
          <edc:SFRMode edc:id="DS.0">
            <edc:SFRFieldDef edc:cname="C@TXD" edc:desc="" edc:islanghidden="true" edc:mask="0x7fff" edc:name="C@TXD" edc:nzwidth="16"/>
            <edc:SFRFieldDef edc:cname="C@TXD" edc:desc="" edc:mask="0xffff" edc:name="C@TXD" edc:nzwidth="16"/>
          </edc:SFRMode>
        </edc:SFRModeList>
      </edc:SFRDef>
    </edc:SelectSFR>
  </edc:MuxedSFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF1SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF1SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF1EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF1EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF2SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF2SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF2EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF2EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF3SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF3SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF3EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF3EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF4SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF4SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF4EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF4EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF5SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF5SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF5EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF5EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF6SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF6SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF6EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF6EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF7SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF7SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF7EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF7EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF8SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF8SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF8EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF8EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF9SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF9SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF9EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF9EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF10SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF10SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF10EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF10EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF11SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF11SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF11EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF11EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF12SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF12SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF12EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF12EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF13SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF13SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF13EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF13EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF14SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF14SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF14EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF14EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnn-n-nn" edc:cname="C@RXF15SID" edc:desc="" edc:impl="0xffeb" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxx-x-xx" edc:name="C@RXF15SID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxx-x-xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID16" edc:desc="" edc:mask="0x1" edc:name="EID16" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID17" edc:desc="" edc:mask="0x1" edc:name="EID17" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="EXIDE" edc:desc="" edc:mask="0x1" edc:name="EXIDE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="SID0" edc:desc="" edc:mask="0x1" edc:name="SID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID1" edc:desc="" edc:mask="0x1" edc:name="SID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID2" edc:desc="" edc:mask="0x1" edc:name="SID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID3" edc:desc="" edc:mask="0x1" edc:name="SID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID4" edc:desc="" edc:mask="0x1" edc:name="SID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID5" edc:desc="" edc:mask="0x1" edc:name="SID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID6" edc:desc="" edc:mask="0x1" edc:name="SID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID7" edc:desc="" edc:mask="0x1" edc:name="SID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID8" edc:desc="" edc:mask="0x1" edc:name="SID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID9" edc:desc="" edc:mask="0x1" edc:name="SID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="SID10" edc:desc="" edc:mask="0x1" edc:name="SID10" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0x3" edc:name="EID" edc:nzwidth="2"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="SID" edc:desc="" edc:mask="0x7ff" edc:name="SID" edc:nzwidth="11"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="C@RXF15EID" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="C@RXF15EID" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="EID0" edc:desc="" edc:mask="0x1" edc:name="EID0" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID1" edc:desc="" edc:mask="0x1" edc:name="EID1" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID2" edc:desc="" edc:mask="0x1" edc:name="EID2" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID3" edc:desc="" edc:mask="0x1" edc:name="EID3" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID4" edc:desc="" edc:mask="0x1" edc:name="EID4" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID5" edc:desc="" edc:mask="0x1" edc:name="EID5" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID6" edc:desc="" edc:mask="0x1" edc:name="EID6" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID7" edc:desc="" edc:mask="0x1" edc:name="EID7" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID8" edc:desc="" edc:mask="0x1" edc:name="EID8" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID9" edc:desc="" edc:mask="0x1" edc:name="EID9" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID10" edc:desc="" edc:mask="0x1" edc:name="EID10" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID11" edc:desc="" edc:mask="0x1" edc:name="EID11" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID12" edc:desc="" edc:mask="0x1" edc:name="EID12" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID13" edc:desc="" edc:mask="0x1" edc:name="EID13" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID14" edc:desc="" edc:mask="0x1" edc:name="EID14" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="EID15" edc:desc="" edc:mask="0x1" edc:name="EID15" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="EID" edc:desc="" edc:mask="0xffff" edc:name="EID" edc:nzwidth="16"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
  </edc:SFRDef>
</edc:Module>