<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="01017-PMDx" edc:modid="TBAA_PMDx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x2" edc:locsize="0x2" edc:wordimpl="0xffff" edc:wordinit="0x0" edc:wordsafe="0xffff" edc:wordsize="0x2"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="PMD1" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0000000x00000x00" edc:name="PMD1" edc:nzwidth="0x10" edc:por="0000000x00000x00">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="AD1MD" edc:desc="" edc:mask="0x1" edc:name="AD1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="C1MD" edc:desc="" edc:mask="0x1" edc:name="C1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="C2MD" edc:desc="" edc:mask="0x1" edc:name="C2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SPI1MD" edc:desc="" edc:mask="0x1" edc:name="SPI1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SPI2MD" edc:desc="" edc:mask="0x1" edc:name="SPI2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="U1MD" edc:desc="" edc:mask="0x1" edc:name="U1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="U2MD" edc:desc="" edc:mask="0x1" edc:name="U2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="I2C1MD" edc:desc="" edc:mask="0x1" edc:name="I2C1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DCIMD" edc:desc="" edc:mask="0x1" edc:name="DCIMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWMMD" edc:desc="" edc:mask="0x1" edc:name="PWMMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="QEI1MD" edc:desc="" edc:mask="0x1" edc:name="QEI1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T1MD" edc:desc="" edc:mask="0x1" edc:name="T1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T2MD" edc:desc="" edc:mask="0x1" edc:name="T2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T3MD" edc:desc="" edc:mask="0x1" edc:name="T3MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T4MD" edc:desc="" edc:mask="0x1" edc:name="T4MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T5MD" edc:desc="" edc:mask="0x1" edc:name="T5MD" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="PMD2" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxx0000xxxx0000" edc:name="PMD2" edc:nzwidth="0x10" edc:por="xxxx0000xxxx0000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="OC1MD" edc:desc="" edc:mask="0x1" edc:name="OC1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC2MD" edc:desc="" edc:mask="0x1" edc:name="OC2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC3MD" edc:desc="" edc:mask="0x1" edc:name="OC3MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC4MD" edc:desc="" edc:mask="0x1" edc:name="OC4MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC5MD" edc:desc="" edc:mask="0x1" edc:name="OC5MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC6MD" edc:desc="" edc:mask="0x1" edc:name="OC6MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC7MD" edc:desc="" edc:mask="0x1" edc:name="OC7MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC8MD" edc:desc="" edc:mask="0x1" edc:name="OC8MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC1MD" edc:desc="" edc:mask="0x1" edc:name="IC1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC2MD" edc:desc="" edc:mask="0x1" edc:name="IC2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC3MD" edc:desc="" edc:mask="0x1" edc:name="IC3MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC4MD" edc:desc="" edc:mask="0x1" edc:name="IC4MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC5MD" edc:desc="" edc:mask="0x1" edc:name="IC5MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC6MD" edc:desc="" edc:mask="0x1" edc:name="IC6MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC7MD" edc:desc="" edc:mask="0x1" edc:name="IC7MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC8MD" edc:desc="" edc:mask="0x1" edc:name="IC8MD" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnn-nnnnnn-nnnn" edc:cname="PMD3" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxx-0xxxx0-xx0x" edc:name="PMD3" edc:nzwidth="16" edc:por="xxxx-0xxxx0-xx0x">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="AD2MD" edc:desc="" edc:mask="0x1" edc:name="AD2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="I2C2MD" edc:desc="" edc:mask="0x1" edc:name="I2C2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="I2C3MD" edc:desc="" edc:mask="0x1" edc:name="I2C3MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="U3MD" edc:desc="" edc:mask="0x1" edc:name="U3MD" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="QEI2MD" edc:desc="" edc:mask="0x1" edc:name="QEI2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DAC1MD" edc:desc="" edc:mask="0x1" edc:name="DAC1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="CRCMD" edc:desc="" edc:mask="0x1" edc:name="CRCMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PMPMD" edc:desc="" edc:mask="0x1" edc:name="PMPMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="RTCCMD" edc:desc="" edc:mask="0x1" edc:name="RTCCMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="CMPMD" edc:desc="" edc:mask="0x1" edc:name="CMPMD" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="T6MD" edc:desc="" edc:mask="0x1" edc:name="T6MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T7MD" edc:desc="" edc:mask="0x1" edc:name="T7MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T8MD" edc:desc="" edc:mask="0x1" edc:name="T8MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T9MD" edc:desc="" edc:mask="0x1" edc:name="T9MD" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="----------nn-nnn" edc:cname="PMD4" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="----------xx0xxx" edc:name="PMD4" edc:nzwidth="16" edc:por="----------xx0xxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="USB1MD" edc:desc="" edc:mask="0x1" edc:name="USB1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="LVDMD" edc:desc="" edc:mask="0x1" edc:name="LVDMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="CTMUMD" edc:desc="" edc:mask="0x1" edc:name="CTMUMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="REFOMD" edc:desc="" edc:mask="0x1" edc:name="REFOMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="EEMD" edc:desc="" edc:mask="0x1" edc:name="EEMD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="U4MD" edc:desc="" edc:mask="0x1" edc:name="U4MD" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="PMD5" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="PMD5" edc:nzwidth="16" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="OC9MD" edc:desc="" edc:mask="0x1" edc:name="OC9MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC10MD" edc:desc="" edc:mask="0x1" edc:name="OC10MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC11MD" edc:desc="" edc:mask="0x1" edc:name="OC11MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC12MD" edc:desc="" edc:mask="0x1" edc:name="OC12MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC13MD" edc:desc="" edc:mask="0x1" edc:name="OC13MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC14MD" edc:desc="" edc:mask="0x1" edc:name="OC14MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC15MD" edc:desc="" edc:mask="0x1" edc:name="OC15MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OC16MD" edc:desc="" edc:mask="0x1" edc:name="OC16MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC9MD" edc:desc="" edc:mask="0x1" edc:name="IC9MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC10MD" edc:desc="" edc:mask="0x1" edc:name="IC10MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC11MD" edc:desc="" edc:mask="0x1" edc:name="IC11MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC12MD" edc:desc="" edc:mask="0x1" edc:name="IC12MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC13MD" edc:desc="" edc:mask="0x1" edc:name="IC13MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC14MD" edc:desc="" edc:mask="0x1" edc:name="IC14MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC15MD" edc:desc="" edc:mask="0x1" edc:name="IC15MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="IC16MD" edc:desc="" edc:mask="0x1" edc:name="IC16MD" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnn------nn" edc:cname="PMD6" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="00000000------xx" edc:name="PMD6" edc:nzwidth="0x10" edc:por="00000000------xx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="SPI3MD" edc:desc="" edc:mask="0x1" edc:name="SPI3MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SPI4MD" edc:desc="" edc:mask="0x1" edc:name="SPI4MD" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="6"/>
        <edc:SFRFieldDef edc:cname="PWM1MD" edc:desc="" edc:mask="0x1" edc:name="PWM1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWM2MD" edc:desc="" edc:mask="0x1" edc:name="PWM2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWM3MD" edc:desc="" edc:mask="0x1" edc:name="PWM3MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWM4MD" edc:desc="" edc:mask="0x1" edc:name="PWM4MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWM5MD" edc:desc="" edc:mask="0x1" edc:name="PWM5MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWM6MD" edc:desc="" edc:mask="0x1" edc:name="PWM6MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWM7MD" edc:desc="" edc:mask="0x1" edc:name="PWM7MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="PWM8MD" edc:desc="" edc:mask="0x1" edc:name="PWM8MD" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="--------nnnn---n" edc:cname="PMD7" edc:desc="" edc:impl="0x0" edc:isindirect="false" edc:isvolatile="true" edc:mclr="--------xxxx---0" edc:name="PMD7" edc:nzwidth="0x10" edc:por="--------xxxx----">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="PWM9MD" edc:desc="" edc:mask="0x1" edc:name="PWM9MD" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="3"/>
        <edc:SFRFieldDef edc:cname="DMA0MD" edc:desc="" edc:mask="0x1" edc:name="DMA0MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA4MD" edc:desc="" edc:mask="0x1" edc:name="DMA4MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA8MD" edc:desc="" edc:mask="0x1" edc:name="DMA8MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA12MD" edc:desc="" edc:mask="0x1" edc:name="DMA12MD" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:AdjustPoint edc:offset="1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="DS.1">
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="DMA1MD" edc:desc="" edc:mask="0x1" edc:name="DMA1MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA5MD" edc:desc="" edc:mask="0x1" edc:name="DMA5MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA9MD" edc:desc="" edc:mask="0x1" edc:name="DMA9MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA13MD" edc:desc="" edc:mask="0x1" edc:name="DMA13MD" edc:nzwidth="1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="DS.2">
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="DMA2MD" edc:desc="" edc:mask="0x1" edc:name="DMA2MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA6MD" edc:desc="" edc:mask="0x1" edc:name="DMA6MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA10MD" edc:desc="" edc:mask="0x1" edc:name="DMA10MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA14MD" edc:desc="" edc:mask="0x1" edc:name="DMA14MD" edc:nzwidth="1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="DS.3">
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="DMA3MD" edc:desc="" edc:mask="0x1" edc:name="DMA3MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA7MD" edc:desc="" edc:mask="0x1" edc:name="DMA7MD" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="DMA11MD" edc:desc="" edc:mask="0x1" edc:name="DMA11MD" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
</edc:Module>