<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="00995" edc:modid="ocmp_v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x2" edc:locsize="0x2" edc:wordimpl="0xffff" edc:wordinit="0x0" edc:wordsafe="0xffff" edc:wordsize="0x2"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="OC@RS" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="uuuuuuuuuuuuuuuu" edc:name="OC@RS" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="OC@RS" edc:desc="" edc:islanghidden="true" edc:mask="0xffff" edc:name="OC@RS" edc:nzwidth="0x10"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Integer"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="OC@R" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="uuuuuuuuuuuuuuuu" edc:name="OC@R" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="OC@R" edc:desc="" edc:islanghidden="true" edc:mask="0xffff" edc:name="OC@R" edc:nzwidth="0x10"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Integer"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="--n--------rnnnn" edc:cname="OC@CON" edc:desc="" edc:impl="0x201f" edc:isindirect="false" edc:isvolatile="true" edc:mclr="--0--------00000" edc:name="OC@CON" edc:nzwidth="0x10" edc:por="--0--------00000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:aspect="Number" edc:cname="OCM" edc:desc="" edc:mask="0x7" edc:name="OCM" edc:nzwidth="0x3"/>
        <edc:SFRFieldDef edc:aspect="Pattern" edc:cname="OCTSEL" edc:desc="" edc:mask="0x1" edc:name="OCTSEL" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:aspect="Pattern" edc:cname="OCFLT" edc:desc="" edc:mask="0x1" edc:name="OCFLT" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="8"/>
        <edc:SFRFieldDef edc:aspect="Pattern" edc:cname="OCSIDL" edc:desc="" edc:mask="0x1" edc:name="OCSIDL" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="OCM0" edc:desc="" edc:mask="0x1" edc:name="OCM0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OCM1" edc:desc="" edc:mask="0x1" edc:name="OCM1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="OCM2" edc:desc="" edc:mask="0x1" edc:name="OCM2" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
    <edc:FreezeBit edc:freezeval="1" edc:name="OUTPUT COMPARE @" edc:pos="0xe"/>
  </edc:SFRDef>
</edc:Module>
