<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="00932" edc:modid="tmr_32b_v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x2" edc:locsize="0x2" edc:wordimpl="0xffff" edc:wordinit="0x0" edc:wordsafe="0xffff" edc:wordsize="0x2"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="TMR%x%" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="TMR%x%" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="TMR%x%" edc:desc="" edc:mask="0xffff" edc:name="TMR%x%" edc:nzwidth="0x10"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Integer"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="TMR%y%HLD" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="TMR%y%HLD" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="TMR%y%HLD" edc:desc="" edc:mask="0xffff" edc:name="TMR%y%HLD" edc:nzwidth="0x10"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Integer"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="TMR%y%" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxxxxxxxxxx" edc:name="TMR%y%" edc:nzwidth="0x10" edc:por="xxxxxxxxxxxxxxxx">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="TMR%y%" edc:desc="" edc:mask="0xffff" edc:name="TMR%y%" edc:nzwidth="0x10"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Integer"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="PR%x%" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="1111111111111111" edc:name="PR%x%" edc:nzwidth="0x10" edc:por="1111111111111111">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="PR%x%" edc:desc="" edc:mask="0xffff" edc:name="PR%x%" edc:nzwidth="0x10"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Integer"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnnnnnnnnnn" edc:cname="PR%y%" edc:desc="" edc:impl="0xffff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="1111111111111111" edc:name="PR%y%" edc:nzwidth="0x10" edc:por="1111111111111111">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="PR%y%" edc:desc="" edc:mask="0xffff" edc:name="PR%y%" edc:nzwidth="0x10"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Integer"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="n-n------nnnn-n-" edc:cname="T%x%CON" edc:desc="" edc:impl="0xa07a" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0-0------0000-0-" edc:name="T%x%CON" edc:nzwidth="0x10" edc:por="0-0------0000-0-">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="TCS" edc:desc="" edc:mask="0x1" edc:name="TCS" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="T32" edc:desc="" edc:mask="0x1" edc:name="T32" edc:nzwidth="0x1"/>
        <edc:SFRFieldDef edc:cname="TCKPS" edc:desc="" edc:mask="0x3" edc:name="TCKPS" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="TGATE" edc:desc="" edc:mask="0x1" edc:name="TGATE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="6"/>
        <edc:SFRFieldDef edc:cname="TSIDL" edc:desc="" edc:mask="0x1" edc:name="TSIDL" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="TON" edc:desc="" edc:mask="0x1" edc:name="TON" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="TCKPS0" edc:desc="" edc:mask="0x1" edc:name="TCKPS0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="TCKPS1" edc:desc="" edc:mask="0x1" edc:name="TCKPS1" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
    <edc:FreezeBit edc:freezeval="1" edc:name="TIMER%x%" edc:pos="0xe"/>
  </edc:SFRDef>
  <edc:SFRDef edc:access="n-n------nnn--n-" edc:cname="T%y%CON" edc:desc="" edc:impl="0xa072" edc:isindirect="false" edc:isvolatile="true" edc:mclr="0-0------000--0-" edc:name="T%y%CON" edc:nzwidth="0x10" edc:por="0-0------000--0-">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="TCS" edc:desc="" edc:mask="0x1" edc:name="TCS" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="2"/>
        <edc:SFRFieldDef edc:cname="TCKPS" edc:desc="" edc:mask="0x3" edc:name="TCKPS" edc:nzwidth="0x2"/>
        <edc:SFRFieldDef edc:cname="TGATE" edc:desc="" edc:mask="0x1" edc:name="TGATE" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="6"/>
        <edc:SFRFieldDef edc:cname="TSIDL" edc:desc="" edc:mask="0x1" edc:name="TSIDL" edc:nzwidth="0x1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="TON" edc:desc="" edc:mask="0x1" edc:name="TON" edc:nzwidth="0x1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="TCKPS0" edc:desc="" edc:mask="0x1" edc:name="TCKPS0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="TCKPS1" edc:desc="" edc:mask="0x1" edc:name="TCKPS1" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
    <edc:StimInfo edc:stimpcfiles="" edc:stimregfiles="" edc:stimscl="rwb" edc:stimtype="Record"/>
    <edc:FreezeBit edc:freezeval="1" edc:name="TIMER%y%" edc:pos="0xe"/>
  </edc:SFRDef>
</edc:Module>
