<?xml version="1.0" encoding="UTF-8" standalone="no" ?><edc:Module xmlns:edc="http://crownking/edc" edc:dosid="DOS-01474_tmr_Timer1_v5_8bit" edc:modid="tmr_Timer1_v5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://crownking/edc edc/Module.xsd">
  <edc:ArchDef edc:desc="" edc:name="">
    <edc:MemTraits>
      <edc:DataMemTraits edc:addrinc="0x1" edc:locsize="0x1" edc:wordimpl="0xff" edc:wordinit="0x0" edc:wordsafe="0xff" edc:wordsize="0x1"/>
    </edc:MemTraits>
  </edc:ArchDef>
  <edc:SFRDef edc:access="nnnnnnnn" edc:cname="T@GCON" edc:desc="" edc:impl="0xff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="xxxxxxxx" edc:name="T@GCON" edc:nzwidth="8" edc:por="00000x00">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="T@GSS" edc:desc="" edc:mask="0x3" edc:name="T@GSS" edc:nzwidth="2"/>
        <edc:SFRFieldDef edc:cname="T@GVAL" edc:desc="" edc:mask="0x1" edc:name="T@GVAL" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T@GGO_n_T@DONE" edc:desc="" edc:mask="0x1" edc:name="T@GGO_n_T@DONE" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T@G@SE" edc:desc="" edc:mask="0x1" edc:name="T@G@SE" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T@GTM" edc:desc="" edc:mask="0x1" edc:name="T@GTM" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T@GPOL" edc:desc="" edc:mask="0x1" edc:name="T@GPOL" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="TMR@GE" edc:desc="" edc:mask="0x1" edc:name="TMR@GE" edc:nzwidth="1"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:SFRFieldDef edc:cname="T@GSS0" edc:desc="" edc:mask="0x1" edc:name="T@GSS0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T@GSS1" edc:desc="" edc:mask="0x1" edc:name="T@GSS1" edc:nzwidth="1"/>
        <edc:AdjustPoint edc:offset="1"/>
        <edc:SFRFieldDef edc:cname="T@GGO" edc:desc="" edc:mask="0x1" edc:name="T@GGO" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:SFRDef edc:access="nnnnnnnn" edc:cname="T@CON" edc:desc="" edc:impl="0xff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="uuuuuuuu" edc:name="T@CON" edc:nzwidth="8" edc:por="00000000">
    <edc:AliasList/>
    <edc:SFRModeList>
      <edc:SFRMode edc:id="DS.0">
        <edc:SFRFieldDef edc:cname="TMR@ON" edc:desc="" edc:mask="0x1" edc:name="TMR@ON" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="RD16" edc:desc="" edc:mask="0x1" edc:name="RD16" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="nT@SYNC" edc:desc="" edc:mask="0x1" edc:name="nT@SYNC" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="SOSCEN" edc:desc="" edc:mask="0x1" edc:name="SOSCEN" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="TCKPS" edc:desc="" edc:mask="0x3" edc:name="TCKPS" edc:nzwidth="2"/>
        <edc:SFRFieldDef edc:cname="TMR@CS" edc:desc="" edc:mask="0x3" edc:name="TMR@CS" edc:nzwidth="2"/>
      </edc:SFRMode>
      <edc:SFRMode edc:id="LT.0">
        <edc:AdjustPoint edc:offset="4"/>
        <edc:SFRFieldDef edc:cname="T@CKPS0" edc:desc="" edc:mask="0x1" edc:name="T@CKPS0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="T@CKPS1" edc:desc="" edc:mask="0x1" edc:name="T@CKPS1" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="TMR@CS0" edc:desc="" edc:mask="0x1" edc:name="TMR@CS0" edc:nzwidth="1"/>
        <edc:SFRFieldDef edc:cname="TMR@CS1" edc:desc="" edc:mask="0x1" edc:name="TMR@CS1" edc:nzwidth="1"/>
      </edc:SFRMode>
    </edc:SFRModeList>
  </edc:SFRDef>
  <edc:JoinedSFRDef edc:cname="TMR@" edc:desc="" edc:name="TMR@" edc:nzwidth="0x10">
    <edc:SFRModeList/>
    <edc:SFRDef edc:access="nnnnnnnn" edc:cname="TMR@L" edc:desc="" edc:impl="0xff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="uuuuuuuu" edc:name="TMR@L" edc:nzwidth="8" edc:por="xxxxxxxx">
      <edc:AliasList/>
      <edc:SFRModeList>
        <edc:SFRMode edc:id="DS.0">
          <edc:SFRFieldDef edc:cname="TMR@L" edc:desc="" edc:mask="0xff" edc:name="TMR@L" edc:nzwidth="8"/>
        </edc:SFRMode>
      </edc:SFRModeList>
    </edc:SFRDef>
    <edc:SFRDef edc:access="nnnnnnnn" edc:cname="TMR@H" edc:desc="" edc:impl="0xff" edc:isindirect="false" edc:isvolatile="true" edc:mclr="uuuuuuuu" edc:name="TMR@H" edc:nzwidth="8" edc:por="xxxxxxxx">
      <edc:AliasList/>
      <edc:SFRModeList>
        <edc:SFRMode edc:id="DS.0">
          <edc:SFRFieldDef edc:cname="TMR@H" edc:desc="" edc:mask="0xff" edc:name="TMR@H" edc:nzwidth="8"/>
        </edc:SFRMode>
      </edc:SFRModeList>
    </edc:SFRDef>
  </edc:JoinedSFRDef>
</edc:Module>