/*
* generated by Xtext
*/
package hu.e.parser.ui.contentassist;

import hu.e.parser.ui.contentassist.AbstractESyntaxProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ESyntaxProposalProvider extends AbstractESyntaxProposalProvider {

}
