/*
 * generated by Xtext
 */
package hu.e.parser.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ESyntaxExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return hu.e.parser.ui.internal.ESyntaxActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return hu.e.parser.ui.internal.ESyntaxActivator.getInstance().getInjector("hu.e.parser.ESyntax");
	}
	
}
