<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pic"
    nsURI="http://cubussapiens.hu/modembed/pic" nsPrefix="pic">
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationBits">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheme" eType="ecore:EClass ../../hu.cubussapiens.modembed.configuration.model/model/modembed.configuration.ecore#//Scheme"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="words" upperBound="-1"
        eType="#//ConfigurationWord" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wordsize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationWord">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//ConfigurationField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="ecore:EClass ../../hu.cubussapiens.modembed.configuration.model/model/modembed.configuration.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startBit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PicCPUType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//ConfigurationBits"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
