/*
 * generated by Xtext
 */
package hu.cubussapiens.modembed.modularasm;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModularASMRuntimeModule extends hu.cubussapiens.modembed.modularasm.AbstractModularASMRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return MASMTerminalConverters.class;
	}
	
}
