<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://modembed.hu/" nsPrefix="modembedmodel">
  <eSubpackages name="core" nsURI="http://modembed.hu/core" nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//core/MODembedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//core/PackagedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
          eType="#//core/PackagedElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MODembedElement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PackagedElement" abstract="true" eSuperTypes="#//core/NamedElement"/>
  </eSubpackages>
  <eSubpackages name="network" nsURI="http://modembed.hu/network" nsPrefix="network">
    <eClassifiers xsi:type="ecore:EClass" name="NetworkNode" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
          eType="#//network/NetworkInterface" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//core/PackagedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
          eType="#//network/NetworkNode" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
          eType="#//network/Connection" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
          eType="#//network/NetworkInterface">
        <eAnnotations source="reference">
          <details key="scope" value=".."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkInterface" abstract="true"
        eSuperTypes="#//core/NamedElement"/>
    <eSubpackages name="rs232" nsURI="http://modembed.hu/network/rs232" nsPrefix="rs232">
      <eClassifiers xsi:type="ecore:EClass" name="RS232Interface" eSuperTypes="#//network/NetworkInterface"/>
      <eClassifiers xsi:type="ecore:EClass" name="RS232Connection" eSuperTypes="#//network/Connection">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="baudRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="comm" nsURI="http://modembed.hu/comm" nsPrefix="comm">
    <eClassifiers xsi:type="ecore:EClass" name="Frame" abstract="true" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationProtocol" abstract="true"
        eSuperTypes="#//core/PackagedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="frames" upperBound="-1"
          eType="#//comm/Frame" containment="true"/>
    </eClassifiers>
    <eSubpackages name="rs232" nsURI="http://modembed.hu/comm/rs232" nsPrefix="commrs232">
      <eClassifiers xsi:type="ecore:EClass" name="RS232Frame" eSuperTypes="#//comm/Frame">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfBytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
            eType="#//comm/rs232/Field" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Field">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RS232Protocol" eSuperTypes="#//comm/CommunicationProtocol">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="idBitLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
