<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://modembed.hu/" nsPrefix="modembedmodel">
  <eSubpackages name="core" nsURI="http://modembed.hu/core" nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//core/MODembedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A Modelelement, which can be identified by a name. The name is unique locally."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MODembedElement" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the base class of every element in a MODembed model. It specifies some basic concepts that is general in every domain, like a descritpion or traceability."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="origins" upperBound="-1"
          eType="#//core/Origin" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The description of the element"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RootElement" abstract="true" eSuperTypes="#//core/NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Subclasses of this class are used as root elements of MODembed models. The name of a root element is unique in the whole model space."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Origin" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element of traceability. Specifies a link to an object from which the containing element originates in a way (for example through a model transformation)."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelOrigin" eSuperTypes="#//core/Origin">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
          eType="#//core/MODembedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextOrigin" eSuperTypes="#//core/Origin">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="line" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="charStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="charEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eSubpackages name="assembler" nsURI="http://modembed.hu/core/assembler" nsPrefix="assembler">
      <eClassifiers xsi:type="ecore:EClass" name="InstructionSet" eSuperTypes="#//core/RootElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
            eType="#//core/assembler/Instruction" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="extend" eType="#//core/assembler/InstructionSet"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Instruction" eSuperTypes="#//core/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
            eType="#//core/assembler/InstructionParameter" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="words" upperBound="-1"
            eType="#//core/assembler/InstructionWord" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstructionParameter" eSuperTypes="#//core/MODembedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstructionSection" abstract="true"
          eSuperTypes="#//core/MODembedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="shift" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConstantSection" eSuperTypes="#//core/assembler/InstructionSection">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParameterSection" eSuperTypes="#//core/assembler/InstructionSection">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
            eType="#//core/assembler/InstructionParameter"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstructionWord" eSuperTypes="#//core/MODembedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
            eType="#//core/assembler/InstructionSection" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="condition" upperBound="-1"
            eType="#//core/assembler/InstructionWordCondition" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InstructionWordCondition" abstract="true"
          eSuperTypes="#//core/MODembedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="InstructionWordMaskedValueCondition"
          eSuperTypes="#//core/assembler/InstructionWordCondition">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="argument" lowerBound="1"
            eType="#//core/assembler/InstructionParameter"/>
      </eClassifiers>
      <eSubpackages name="code" nsURI="http://modembed.hu/core/assembler/code" nsPrefix="assemblercode">
        <eClassifiers xsi:type="ecore:EClass" name="AssemblerObject" eSuperTypes="#//core/RootElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
              eType="#//core/assembler/code/InstructionCall" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="InstructionCall" eSuperTypes="#//core/MODembedElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
              eType="#//core/assembler/code/InstructionCallParameter" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" eType="#//core/assembler/Instruction"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="InstructionCallParameter" eSuperTypes="#//core/MODembedElement">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//core/assembler/InstructionParameter"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="workflow" nsURI="http://modembed.hu/core/workflow" nsPrefix="workflow">
      <eClassifiers xsi:type="ecore:EClass" name="Workflow" eSuperTypes="#//core/RootElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
            eType="#//core/workflow/WorkflowTask" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WorkflowTask" abstract="true" eSuperTypes="#//core/MODembedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//core/workflow/WorkflowTask">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
            eType="#//core/workflow/TaskParameter" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TaskParameter" eSuperTypes="#//core/MODembedElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="architecture" nsURI="http://modembed.hu/architecture" nsPrefix="architecture">
    <eClassifiers xsi:type="ecore:EClass" name="Architecture" eSuperTypes="#//core/RootElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="heapPointerType" eType="#//abstraction/types/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codePointerType" eType="#//abstraction/types/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instructionSet" eType="#//core/assembler/InstructionSet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memory" upperBound="-1"
          eType="#//architecture/MemorySection" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MemorySection" eSuperTypes="#//core/MODembedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="program" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startAddress" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="abstraction" nsURI="http://modembed.hu/abstraction" nsPrefix="abstraction">
    <eSubpackages name="types" nsURI="http://modembed.hu/abstraction/types" nsPrefix="types">
      <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition" abstract="true"
          eSuperTypes="#//core/MODembedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeDefinition" abstract="true"
          eSuperTypes="#//abstraction/types/TypeDefinition"/>
      <eClassifiers xsi:type="ecore:EClass" name="CompositeTypeDefinition" abstract="true"
          eSuperTypes="#//abstraction/types/TypeDefinition"/>
      <eClassifiers xsi:type="ecore:EClass" name="UnsignedTypeDefinition" eSuperTypes="#//abstraction/types/PrimitiveTypeDefinition">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReferenceTypeDefinition" eSuperTypes="#//abstraction/types/CompositeTypeDefinition">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//abstraction/types/Type"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PointerTypeDefinition" eSuperTypes="#//abstraction/types/CompositeTypeDefinition">
        <eStructuralFeatures xsi:type="ecore:EReference" name="pointerType" lowerBound="1"
            eType="#//abstraction/types/TypeDefinition" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayDefinition" eSuperTypes="#//abstraction/types/PointerTypeDefinition"/>
      <eClassifiers xsi:type="ecore:EClass" name="StructureTypeDefinition" eSuperTypes="#//abstraction/types/CompositeTypeDefinition">
        <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
            eType="#//abstraction/types/StructureTypeElement" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StructureTypeElement" eSuperTypes="#//core/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//abstraction/types/TypeDefinition" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CodeLabelTypeDefinition" eSuperTypes="#//abstraction/types/PrimitiveTypeDefinition"/>
      <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//core/RootElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
            eType="#//abstraction/types/TypeDefinition" containment="true"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="behavior" nsURI="http://modembed.hu/behavior" nsPrefix="behavior">
      <eClassifiers xsi:type="ecore:EClass" name="SequentialBehavior" eSuperTypes="#//core/RootElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="symbols" upperBound="-1"
            eType="#//abstraction/behavior/Symbol" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
            eType="#//abstraction/behavior/SequentialAction" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="#//core/NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//abstraction/types/TypeDefinition"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="external" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SequentialAction" abstract="true"
          eSuperTypes="#//core/MODembedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="CodeSymbolPlacement" eSuperTypes="#//abstraction/behavior/SequentialAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="#//abstraction/behavior/Symbol"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AtomicOperationExecution" eSuperTypes="#//abstraction/behavior/SequentialAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
            eType="#//abstraction/behavior/Symbol"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BehaviorCall" eSuperTypes="#//abstraction/behavior/SequentialAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="argumentMappings" upperBound="-1"
            eType="#//abstraction/behavior/SymbolMapping" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SymbolMapping" eSuperTypes="#//core/MODembedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="local" eType="#//abstraction/behavior/Symbol"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="remote" eType="#//abstraction/behavior/Symbol"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SymbolValueMap" eSuperTypes="#//core/RootElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
            eType="#//abstraction/behavior/SymbolValueAssignment" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SymbolValueAssignment" eSuperTypes="#//core/MODembedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="#//abstraction/behavior/Symbol"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="indirectionLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eSubpackages name="platform" nsURI="http://modembed.hu/platform" nsPrefix="platform">
        <eClassifiers xsi:type="ecore:EClass" name="PlatformDefinition" eSuperTypes="#//core/RootElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="refine" eType="#//abstraction/behavior/platform/PlatformDefinition"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
              eType="#//abstraction/behavior/platform/OperationDefinition" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="OperationDefinition" eSuperTypes="#//core/MODembedElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
              eType="#//abstraction/behavior/platform/OperationArgument" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
              eType="#//abstraction/behavior/platform/OperationStep" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="OperationArgument" eSuperTypes="#//core/NamedElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//abstraction/types/TypeDefinition"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="indirectionLevel"
              eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="InstructionCallOperationStep"
            eSuperTypes="#//abstraction/behavior/platform/OperationStep">
          <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" eType="#//core/assembler/Instruction"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
              eType="#//abstraction/behavior/platform/InstructionParameterMapping"
              containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="OperationStep" abstract="true"
            eSuperTypes="#//core/MODembedElement"/>
        <eClassifiers xsi:type="ecore:EClass" name="InstructionParameterMapping" eSuperTypes="#//core/MODembedElement">
          <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//abstraction/behavior/platform/OperationArgument"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="bitOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
