<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="project"
    nsURI="http://cubusspiens.hu/modembed/project" nsPrefix="project">
  <eClassifiers xsi:type="ecore:EClass" name="ProjectConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcedirs" upperBound="-1"
        eType="#//Directory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="builds" upperBound="-1"
        eType="#//MainModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//SettingsExtension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainModule" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Output" eType="#//Directory"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SettingsExtension" abstract="true"/>
</ecore:EPackage>
