/*
* generated by Xtext
*/
package hu.cubussapiens.modembed.modularasm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModularASMAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/cubussapiens/modembed/modularasm/parser/antlr/internal/InternalModularASM.tokens");
	}
}
